[extension.jpg]
run = "imv \"$@\""
block = false

[extension.png]
run = "imv \"$@\""
block = false

[extension.jpeg]
run = "imv \"$@\""
block = false

[extension.webp]
run = "imv \"$@\""
block = false

[extension.gif]
run = "imv \"$@\""
block = false

[extension.bmp]
run = "imv \"$@\""
block = false
